# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Kitchen Dijon"
email:
description: "bliki for my thoughts"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dijonkitchen.github.io" # the base hostname & protocol for your site
github_username: dijonkitchen
linkedin_username: jonathanschen

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown

# Outputting
permalink: "/:slug"
paginate: 5
paginate_path: "/page:num"

# Whitelist public resources
include: [".well-known"]